module.exports.descriptors = [
    'Mountaineering',
    'rock climbing',
    'sport climbing',
    'camping',
    'hot air ballooning',
    'skydiving',
    'parasailing',
    'scuba diving',
    'deep-sea diving',
    'sailing',
    'windsurfing',
    'rafting',
    'kayaking',
    'ziplining',
    'mountain biking',
    'trekking'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]
